[package]
name = "backend"
version = "0.1.0"
authors = [
    "Jack Hanslope <jackhansp@btinternet.com>",
    "Jakob Schmutz <jakob@schmutz.co.uk>",
]
edition = "2018"

[dependencies]
rocket = "0.4.4"
rocket_contrib = {version = "0.4.4", features = ["json"]}
skat = { path = "../" }
